# Generated by Django 3.2.14 on 2022-07-13 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalMRD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MRD', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='addnote',
            name='MRD',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='app.hospitalmrd'),
        ),
        migrations.AlterField(
            model_name='clinicalpharmacist',
            name='MRD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hospitalmrd'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hospitalmrd'),
        ),
        migrations.DeleteModel(
            name='WeatherStation',
        ),
    ]
