# Generated by Django 3.2.14 on 2022-08-18 15:39

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_clinicalpharmacist_child_pugh_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalpharmacist',
            name='Dose_adjustment_LI',
        ),
        migrations.RemoveField(
            model_name='clinicalpharmacist',
            name='renal_impairment',
        ),
        migrations.AlterField(
            model_name='clinicalpharmacist',
            name='AB_INTERVENTION',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Intervention', (('Escalution-need', 'Escalution'), ('De-escalution-need', 'De-escalution'), ('Renal-dose-adjustment', 'Renal-dose-adjustment'), ('hepatic-dose-adjustment', 'hepatic-dose-adjustment'), ('Renal-dose-adjustment', 'Renal-dose-adjustment'), ('Discontinue', 'Discontinue')))], default=False, max_length=512),
        ),
        migrations.AlterField(
            model_name='clinicalpharmacist',
            name='Child_pugh_score',
            field=models.FloatField(default=True),
        ),
        migrations.AlterField(
            model_name='clinicalpharmacist',
            name='Electrolytes_imbalance',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Na', 'Na'), ('K', 'K'), ('Mg', 'Mg'), ('Po4', 'Po4'), ('Ca', 'Ca')], default=False, max_length=512),
        ),
        migrations.AlterField(
            model_name='clinicalpharmacist',
            name='GFR',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalpharmacist',
            name='Infection',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('UA', 'UA'), ('Markers', 'Markers'), ('Fever', 'Fever'), ('Culture', 'Culture'), ('X-Ray', 'X-Ray'), ('Swab', 'Swab')], default=False, max_length=512),
        ),
        migrations.AlterField(
            model_name='clinicalpharmacist',
            name='MP_LIST',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Monitoring Parameter', (('Markers', 'Markers'), ('Platelets', 'Platelets'), ('QT-c', 'QT-c'), ('Level', 'Level'), ('Interaction', 'Interaction'), ('Candida_Score', 'Candida_Score'), ('Lactate', 'Lactate')))], default=False, max_length=512),
        ),
        migrations.AlterField(
            model_name='clinicalpharmacist',
            name='Metabolic_num',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalpharmacist',
            name='QT_C_num',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalpharmacist',
            name='Respiratory_num',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalpharmacist',
            name='T_BG',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('G1', (('Hypoglycomic', 'Hypoglycomic'), ('Glucagon', 'Glucagon'), ('D50%', 'D50%'), ('D5%/D10%', 'D5%/D10%'))), ('G2', (('koton', 'koton'), ('Hydration', 'Hydration'))), ('G3', (('Hyperglycemia', 'Hyperglycemia'), ('Insulin Infusion', 'Insulin Infusion'), ('DKA protocol', 'DKA protocol'), ('SQ Sliding Scale', 'SQ Sliding Scale'), ('Long acting insulin', 'Long acting insulin')))], default=False, max_length=512),
        ),
        migrations.AlterField(
            model_name='clinicalpharmacist',
            name='Treatment',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AB-A', (('Ampicillin', 'Ampicillin'), ('Amoxiclav', 'Amoxiclav'), ('Amikacin', 'Amikacin'), ('Azithromycin', 'Azithromycin'), ('Anidulafungin', 'Anidulafungin'), ('Albendazole', 'Albendazole'), ('Acyclovir', 'Acyclovir'))), ('AB-C', (('Cefazoline', 'Cefazoline'), ('Ceftriaxone', 'Ceftriaxone'), ('Cefotaxime', 'Cefotaxime'), ('Cefepim', 'Cefepim'), ('Ceftarolin', 'Ceftarolin'), ('Ceftazidim', 'Ceftazidim'), ('Ceftazidim/avibactam', 'Ceftazidim/avibactam'), ('Cftobiprole', 'Cftobiprole'))), ('AB-E', (('Ertapenem', 'Ertapenem'), ('Tigecycline', 'Tigecycline'))), ('AB-F', (('Flucloxacillin ', 'Flucloxacillin'), ('Fluconazole', 'Fluconazole'))), ('AB-G', (('Gentamycin', 'Gentamycin'), ('Ganciclovir', 'Ganciclovir'))), ('AB-P', (('Penicillin G', 'Penicillin G'), ('Piperacillin/tazobactam', 'Piperacillin/tazobactam'), ('Pentamidine', 'Pentamidine'))), ('AB-V', (('Vancomycin', 'Vancomycin'), ('Voriconazole', 'Voriconazole'))), ('AB-T', (('Teicoplanin', 'Teicoplanin'), ('Tigecycline', 'Tigecycline'))), ('AB-M', (('Meropenem', 'Meropenem'), ('Metronidazole', 'Metronidazole'))), ('AB-I', (('Imipenem cilastatin', 'Imipenem cilastatin'), ('Isavuconazole', 'Isavuconazole'))), ('AB-L', (('Levofloxacin', 'Levofloxacin'), ('Linezolid', 'Linezolid'))), ('AB-V', (('Voriconazole', 'Voriconazole'),)), ('AB-G', (('Ganciclovir', 'Ganciclovir'),)), ('AB-R', (('Remdesivir', 'Remdesivir'),))], default=False, max_length=512),
        ),
        migrations.AlterField(
            model_name='clinicalpharmacist',
            name='VITALS',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('stable', 'stable'), ('tech carbon', 'techcarbon'), ('tachypnea', 'tachypnea'), ('htn', 'HTN'), ('bradycardia', 'bradycardia'), ('bradypnea', 'bradypnea'), ('hypotension', 'hypotension'), ('Fever', 'Fever')], default=False, max_length=512),
        ),
    ]
