# Generated by Django 3.2.14 on 2022-08-18 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220818_1939'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temperature',
        ),
    ]
